<a href="https://colab.research.google.com/github/Gus-1003/ENEM_2021-Data_analysis/blob/main/Conclus%C3%A3o/Sistema_Enem_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bibliotecas

In [1]:
# Biblioteca Pandas: usada para manipulação de dados em formato tabular, facilitando a análise e processamento desses dados;
import pandas as pd

# NumPy oferece operações matemáticas poderosas para arrays e matrizes;
import numpy as np

# A biblioteca Matplotlib é uma das mais usadas para visualização de dados, oferecendo diversas ferramentas e opções de plotagem;
import matplotlib.pyplot as plt

# A biblioteca Seaborn é construída em cima do Matplotlib, adicionando ainda mais recursos para criar gráficos mais sofisticados e visualmente atraentes.
import seaborn as sns

In [2]:
# importe da biblioteca drive do Google Colab, que é usada para fazer a conexão com o Google Drive.
from google.colab import drive

# o método mount() para montar o Google Drive na sessão atual do Colab. Isso significa que a sessão do Colab agora terá acesso aos arquivos armazenados no Google Drive.
drive.mount('/content/drive/')

''' comando %cd é usado para mudar o diretório atual para a pasta MyDrive dentro do Google Drive, para que os arquivos dentro dessa
pasta possam ser facilmente acessados pelo código em Python que será executado na sessão do Colab.'''

%cd /content/drive/MyDrive/

Mounted at /content/drive/
/content/drive/MyDrive

# Leitura dataset:

In [3]:
microdados = '/content/drive/MyDrive/Pesquisa_Enem/Base de Dados/MICRODADOS_ENEM_2019.csv'

In [4]:
# Divide o caminho do arquivo e obtém o nome do frame
nome_completo = microdados.split('/')
nome = nome_completo[6].split('_')
amostra = nome[2]

print(microdados)
print(amostra)

/content/drive/MyDrive/Pesquisa_Enem/Base de Dados/MICRODADOS_ENEM_2019.csv
2019.csv

In [5]:
"""Para carregar os dados em Python, você pode usar a função read_csv() do pandas para carregar dados de um arquivo CSV,
ou outras funções semelhantes para carregar dados de outros tipos de arquivos:"""

dados = pd.read_csv(microdados, encoding='latin-1', delimiter=";", quotechar='"', usecols=['TP_PRESENCA_CN', 'CO_PROVA_CN','NU_NOTA_CN','TX_RESPOSTAS_CN'])
dados

,TP_PRESENCA_CN,CO_PROVA_CN,NU_NOTA_CN,TX_RESPOSTAS_CN
0,0,NaN,NaN,NaN
1,0,NaN,NaN,NaN
2,0,NaN,NaN,NaN
3,1,504.0,483.8,BACCEEBEECDBEDDAEECDEDEADEBBCDBCAACADEEACCBBD
4,1,504.0,513.6,EEBEDEEEEEBDCEEBEEEEABEEBEEBAEDEECECCDBCECEAE
...,...,...,...,...
5095166,0,NaN,NaN,NaN
5095167,0,NaN,NaN,NaN
5095168,0,NaN,NaN,NaN
5095169,0,NaN,NaN,NaN
5095170,0,NaN,NaN,NaN

# Pré-processamento:

## Garantia da Presença:

In [6]:
'''O argumento index do método drop() é utilizado para remover as linhas que foram selecionadas, utilizando o atributo index do DataFrame resultante
da seleção: dados[dados.TP_PRESENCA_CN == 0].index.'''

# Apagando o registro dos alunos ausentes:
dados = dados.drop(index=dados[dados.TP_PRESENCA_CN == 0].index)

# Apagando o registro dos alunos eliminados:
dados = dados.drop(index=dados[dados.TP_PRESENCA_CN == 2].index)

dados.shape

(3710335, 4)

In [7]:
dados

,TP_PRESENCA_CN,CO_PROVA_CN,NU_NOTA_CN,TX_RESPOSTAS_CN
3,1,504.0,483.8,BACCEEBEECDBEDDAEECDEDEADEBBCDBCAACADEEACCBBD
4,1,504.0,513.6,EEBEDEEEEEBDCEEBEEEEABEEBEEBAEDEECECCDBCECEAE
5,1,505.0,563.7,DCDBDEDCDDBCBEADBEBBCDBDBDEBEBACABDBDADEDACAE
6,1,505.0,484.6,BADEBCACADECAEAAAECCCDEACCEA.ECCDDCECBEBADAAC
9,1,505.0,543.9,BADADDBADBBECEBBCECBCBEBBBCBABDECDEACADDADCEE
...,...,...,...,...
5095158,1,503.0,391.2,ACDADEAEBACBECDBEBEABDEDEBCCADEDACDBDCAEAEABC
5095160,1,506.0,414.6,BBECABDEDBDCBCADEBBAAEBECEABEEEECAECEBECEDDBE
5095161,1,503.0,370.3,DBEEDBEAAEBDACAABCDBBACDEEAEEA*CBABDDABCEAAAB
5095164,1,503.0,499.6,DADDDCEDCBECDEEBBCBABEDEABCDEEAEEDDBECBECACDD
5095165,1,506.0,409.0,DADECDCEDADCCDEDACDBBDBCEDCBDECEDDACBBBDBEBAA

In [8]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3710335 entries, 3 to 5095165
Data columns (total 4 columns):
 #   Column           Dtype
---  ------           -----
 0   TP_PRESENCA_CN   int64
 1   CO_PROVA_CN      float64
 2   NU_NOTA_CN       float64
 3   TX_RESPOSTAS_CN  object
dtypes: float64(2), int64(1), object(1)
memory usage: 141.5+ MB

## Remoção dos outros tipos de Prova:

In [9]:
dados['CO_PROVA_CN'].value_counts()

505.0    933535
504.0    925530
503.0    924465
506.0    924211
523.0      2089
519.0       505
Name: CO_PROVA_CN, dtype: int64

In [10]:
# Apagando outras provas:
dados = dados[dados['CO_PROVA_CN'] <= 506.0]

## Visualização - Resumo:

In [11]:
dados

,TP_PRESENCA_CN,CO_PROVA_CN,NU_NOTA_CN,TX_RESPOSTAS_CN
3,1,504.0,483.8,BACCEEBEECDBEDDAEECDEDEADEBBCDBCAACADEEACCBBD
4,1,504.0,513.6,EEBEDEEEEEBDCEEBEEEEABEEBEEBAEDEECECCDBCECEAE
5,1,505.0,563.7,DCDBDEDCDDBCBEADBEBBCDBDBDEBEBACABDBDADEDACAE
6,1,505.0,484.6,BADEBCACADECAEAAAECCCDEACCEA.ECCDDCECBEBADAAC
9,1,505.0,543.9,BADADDBADBBECEBBCECBCBEBBBCBABDECDEACADDADCEE
...,...,...,...,...
5095158,1,503.0,391.2,ACDADEAEBACBECDBEBEABDEDEBCCADEDACDBDCAEAEABC
5095160,1,506.0,414.6,BBECABDEDBDCBCADEBBAAEBECEABEEEECAECEBECEDDBE
5095161,1,503.0,370.3,DBEEDBEAAEBDACAABCDBBACDEEAEEA*CBABDDABCEAAAB
5095164,1,503.0,499.6,DADDDCEDCBECDEEBBCBABEDEABCDEEAEEDDBECBECACDD
5095165,1,506.0,409.0,DADECDCEDADCCDEDACDBBDBCEDCBDECEDDACBBBDBEBAA

## Reset Index

In [12]:
'''o método reset_index() do objeto DataFrame do pandas para redefinir o índice das linhas do DataFrame dados.'''

dados.reset_index(drop=True, inplace=True)

## Remoção da coluna de presença:

In [13]:
dados.drop('TP_PRESENCA_CN', axis=1, inplace=True)
dados.head()

<ipython-input-13-816f6137eb09>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.drop('TP_PRESENCA_CN', axis=1, inplace=True)

   CO_PROVA_CN  NU_NOTA_CN                                TX_RESPOSTAS_CN
0        504.0       483.8  BACCEEBEECDBEDDAEECDEDEADEBBCDBCAACADEEACCBBD
1        504.0       513.6  EEBEDEEEEEBDCEEBEEEEABEEBEEBAEDEECECCDBCECEAE
2        505.0       563.7  DCDBDEDCDDBCBEADBEBBCDBDBDEBEBACABDBDADEDACAE
3        505.0       484.6  BADEBCACADECAEAAAECCCDEACCEA.ECCDDCECBEBADAAC
4        505.0       543.9  BADADDBADBBECEBBCECBCBEBBBCBABDECDEACADDADCEE

# Processamento:

## Separando as questões:

In [14]:
# Identificando a quantidade de quetões - Esse código é um exemplo de como criar uma lista com os valores de uma coluna específica de um DataFrame do pandas.
questoes = []

for i, gabarito in enumerate(list(dados['TX_RESPOSTAS_CN'].loc[0:])):
  questoes.append(gabarito)

## Listando as respostas:

In [15]:
# Construindo as listas de repostas
respostas = []

for i in range(45):
  respostas.append([aluno[i] for aluno in questoes])

## Renomeando as questões:

In [16]:
# Renomeando e preenchendo as Colunas do dicionario
for i in range(45):
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]

<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]
<ipython-input-16-96a5b7f95fb7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.loc[:, 'q' + str(i + 1)] = respostas[i]

# Pré-processamento 2:

In [17]:
dados

,CO_PROVA_CN,NU_NOTA_CN,TX_RESPOSTAS_CN,q1,q2,q3,q4,q5,q6,q7,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,504.0,483.8,BACCEEBEECDBEDDAEECDEDEADEBBCDBCAACADEEACCBBD,B,A,C,C,E,E,B,...,A,D,E,E,A,C,C,B,B,D
1,504.0,513.6,EEBEDEEEEEBDCEEBEEEEABEEBEEBAEDEECECCDBCECEAE,E,E,B,E,D,E,E,...,C,C,D,B,C,E,C,E,A,E
2,505.0,563.7,DCDBDEDCDDBCBEADBEBBCDBDBDEBEBACABDBDADEDACAE,D,C,D,B,D,E,D,...,B,D,A,D,E,D,A,C,A,E
3,505.0,484.6,BADEBCACADECAEAAAECCCDEACCEA.ECCDDCECBEBADAAC,B,A,D,E,B,C,A,...,E,C,B,E,B,A,D,A,A,C
4,505.0,543.9,BADADDBADBBECEBBCECBCBEBBBCBABDECDEACADDADCEE,B,A,D,A,D,D,B,...,A,C,A,D,D,A,D,C,E,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707736,503.0,391.2,ACDADEAEBACBECDBEBEABDEDEBCCADEDACDBDCAEAEABC,A,C,D,A,D,E,A,...,B,D,C,A,E,A,E,A,B,C
3707737,506.0,414.6,BBECABDEDBDCBCADEBBAAEBECEABEEEECAECEBECEDDBE,B,B,E,C,A,B,D,...,C,E,B,E,C,E,D,D,B,E
3707738,503.0,370.3,DBEEDBEAAEBDACAABCDBBACDEEAEEA*CBABDDABCEAAAB,D,B,E,E,D,B,E,...,D,D,A,B,C,E,A,A,A,B
3707739,503.0,499.6,DADDDCEDCBECDEEBBCBABEDEABCDEEAEEDDBECBECACDD,D,A,D,D,D,C,E,...,B,E,C,B,E,C,A,C,D,D
3707740,506.0,409.0,DADECDCEDADCCDEDACDBBDBCEDCBDECEDDACBBBDBEBAA,D,A,D,E,C,D,C,...,C,B,B,B,D,B,E,B,A,A

## Removendo coluna gabarito:

In [18]:
dados.drop('TX_RESPOSTAS_CN', axis=1, inplace=True)
dados

<ipython-input-18-ea43a6a9299b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.drop('TX_RESPOSTAS_CN', axis=1, inplace=True)

,CO_PROVA_CN,NU_NOTA_CN,q1,q2,q3,q4,q5,q6,q7,q8,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,504.0,483.8,B,A,C,C,E,E,B,E,...,A,D,E,E,A,C,C,B,B,D
1,504.0,513.6,E,E,B,E,D,E,E,E,...,C,C,D,B,C,E,C,E,A,E
2,505.0,563.7,D,C,D,B,D,E,D,C,...,B,D,A,D,E,D,A,C,A,E
3,505.0,484.6,B,A,D,E,B,C,A,C,...,E,C,B,E,B,A,D,A,A,C
4,505.0,543.9,B,A,D,A,D,D,B,A,...,A,C,A,D,D,A,D,C,E,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707736,503.0,391.2,A,C,D,A,D,E,A,E,...,B,D,C,A,E,A,E,A,B,C
3707737,506.0,414.6,B,B,E,C,A,B,D,E,...,C,E,B,E,C,E,D,D,B,E
3707738,503.0,370.3,D,B,E,E,D,B,E,A,...,D,D,A,B,C,E,A,A,A,B
3707739,503.0,499.6,D,A,D,D,D,C,E,D,...,B,E,C,B,E,C,A,C,D,D
3707740,506.0,409.0,D,A,D,E,C,D,C,E,...,C,B,B,B,D,B,E,B,A,A

## Separando os tipos de prova:

In [19]:
# Separação das provas por cor
enemAzul = dados[dados['CO_PROVA_CN'] == 503].reset_index(drop=True)
enemAmarela = dados[dados['CO_PROVA_CN'] == 504].reset_index(drop=True)
enemCinza = dados[dados['CO_PROVA_CN'] == 505].reset_index(drop=True)
enemRosa = dados[dados['CO_PROVA_CN'] == 506].reset_index(drop=True)

## Removendo o codigo da prova:

In [20]:
enemAmarela = enemAmarela.drop('CO_PROVA_CN', axis=1)
enemAmarela

,NU_NOTA_CN,q1,q2,q3,q4,q5,q6,q7,q8,q9,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,483.8,B,A,C,C,E,E,B,E,E,...,A,D,E,E,A,C,C,B,B,D
1,513.6,E,E,B,E,D,E,E,E,E,...,C,C,D,B,C,E,C,E,A,E
2,576.6,B,E,E,A,E,E,B,C,E,...,C,C,C,A,E,D,A,B,D,C
3,455.4,B,B,C,A,C,D,C,B,E,...,C,B,A,C,E,C,B,B,E,A
4,618.2,B,A,C,A,C,E,D,D,E,...,C,B,C,B,E,D,C,D,D,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925525,519.9,C,B,C,A,E,E,D,E,E,...,E,D,C,D,A,A,C,A,E,D
925526,423.8,C,E,B,A,D,D,B,B,C,...,C,E,B,C,D,E,A,C,D,B
925527,433.7,C,E,D,A,E,E,C,E,B,...,E,A,A,B,B,A,C,D,E,B
925528,403.6,B,B,C,D,C,A,A,D,B,...,C,B,B,A,A,D,A,A,D,B
925529,439.5,C,E,B,D,C,D,B,E,E,...,.,A,D,C,D,E,E,D,D,A

## Renomeando a coluna "Nota":

In [21]:
enemAmarela = enemAmarela.rename(columns={'NU_NOTA_CN': 'nota'})

## Azul:

In [22]:
# Primeiro processo
col_mapping = {
    'NU_NOTA_CN': 'nota',
    'q36': 'q1',
    'q37': 'q2',
    'q38': 'q3',
    'q1': 'q4',
    'q2': 'q5',
    'q3': 'q6',
    'q31': 'q7',
    'q32': 'q8',
    'q33': 'q9',
    'q29': 'q10',
    'q30': 'q11',
    'q7': 'q12',
    'q8': 'q13',
    'q9': 'q14',
    'q10': 'q15',
    'q20': 'q16',
    'q21': 'q17',
    'q22': 'q18',
    'q23': 'q19',
    'q24': 'q20',
    'q25': 'q21',
    'q26': 'q22',
    'q27': 'q23',
    'q28': 'q24',
    'q14': 'q25',
    'q15': 'q26',
    'q16': 'q27',
    'q17': 'q28',
    'q18': 'q29',
    'q19': 'q30',
    'q11': 'q31',
    'q12': 'q32',
    'q13': 'q33',
    'q4': 'q34',
    'q5': 'q35',
    'q6': 'q36',
    'q34': 'q37',
    'q35': 'q38',
    'q42': 'q39',
    'q43': 'q40',
    'q44': 'q41',
    'q45': 'q42',
    'q39': 'q43',
    'q40': 'q44',
    'q41': 'q45',
}

enemAzul = enemAzul.loc[:, list(col_mapping.keys())]
enemAzul = enemAzul.rename(columns=col_mapping).reset_index(drop=True)

In [23]:
enemAzul

,nota,q1,q2,q3,q4,q5,q6,q7,q8,q9,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,461.9,E,A,C,C,E,E,B,E,E,...,C,B,B,E,D,B,D,B,D,A
1,394.3,C,D,C,B,D,C,B,B,B,...,B,B,B,B,B,A,C,D,D,C
2,427.3,B,D,C,A,E,D,B,A,A,...,C,B,C,B,D,B,A,B,D,C
3,421.1,C,C,E,C,E,E,B,E,C,...,C,C,A,D,B,A,B,B,A,D
4,442.1,D,A,C,D,C,E,A,C,E,...,A,D,D,B,A,B,C,B,E,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924460,481.1,D,D,C,C,D,D,E,E,E,...,C,A,B,A,D,E,B,B,C,C
924461,475.0,D,B,C,C,D,E,C,E,A,...,C,C,A,E,A,C,C,E,D,C
924462,391.2,B,D,C,A,C,D,E,D,A,...,E,C,D,E,A,B,C,A,E,A
924463,370.3,D,D,A,D,B,E,*,C,B,...,B,A,B,A,A,A,B,B,C,E
924464,499.6,B,E,C,D,A,D,A,E,E,...,C,D,D,A,C,D,D,B,E,C

## Cinza:

In [24]:
# Primeiro processo
col_mapping = {
    'NU_NOTA_CN': 'nota',
    'q13': 'q1',
    'q14': 'q2',
    'q15': 'q3',
    'q43': 'q4',
    'q44': 'q5',
    'q45': 'q6',
    'q16': 'q7',
    'q17': 'q8',
    'q18': 'q9',
    'q19': 'q10',
    'q20': 'q11',
    'q39': 'q12',
    'q40': 'q13',
    'q41': 'q14',
    'q42': 'q15',
    'q27': 'q16',
    'q28': 'q17',
    'q29': 'q18',
    'q36': 'q19',
    'q37': 'q20',
    'q38': 'q21',
    'q33': 'q22',
    'q34': 'q23',
    'q35': 'q24',
    'q24': 'q25',
    'q25': 'q26',
    'q26': 'q27',
    'q30': 'q28',
    'q31': 'q29',
    'q32': 'q30',
    'q21': 'q31',
    'q22': 'q32',
    'q23': 'q33',
    'q10': 'q34',
    'q11': 'q35',
    'q12': 'q36',
    'q8':  'q37',
    'q9':  'q38',
    'q1':  'q39',
    'q2':  'q40',
    'q3': 'q41',
    'q4': 'q42',
    'q5': 'q43',
    'q6': 'q44',
    'q7': 'q45',
}

enemCinza = enemCinza.loc[:, list(col_mapping.keys())]
enemCinza = enemCinza.rename(columns=col_mapping).reset_index(drop=True)

In [25]:
enemCinza

,nota,q1,q2,q3,q4,q5,q6,q7,q8,q9,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,563.7,B,E,A,C,A,E,D,B,E,...,C,C,D,D,C,D,B,D,E,D
1,484.6,A,E,A,A,A,C,A,A,E,...,C,C,A,B,A,D,E,B,C,A
2,543.9,C,E,B,C,E,E,B,C,E,...,E,A,D,B,A,D,A,D,D,B
3,518.2,A,C,C,C,C,E,E,B,E,...,D,B,A,D,A,D,B,B,C,D
4,458.9,D,A,E,C,E,D,C,B,D,...,C,B,B,A,A,A,B,B,D,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933530,457.0,B,C,C,E,B,D,D,B,E,...,A,E,D,B,D,A,C,B,D,D
933531,384.7,B,B,D,C,E,E,D,E,D,...,E,C,D,A,A,A,C,B,E,E
933532,554.2,D,A,C,C,E,E,E,E,E,...,C,B,C,B,C,A,C,D,D,D
933533,492.5,D,E,D,E,E,E,A,E,D,...,C,A,B,C,A,D,E,B,A,C
933534,364.1,B,C,A,D,B,C,A,B,D,...,E,D,A,A,B,C,B,B,C,B

## Rosa:

In [26]:
# Primeiro processo
col_mapping = {
    'NU_NOTA_CN': 'nota',
    'q10': 'q1',
    'q11': 'q2',
    'q12': 'q3',
    'q7': 'q4',
    'q8': 'q5',
    'q9': 'q6',
    'q38': 'q7',
    'q39': 'q8',
    'q40': 'q9',
    'q5': 'q10',
    'q6': 'q11',
    'q1': 'q12',
    'q2': 'q13',
    'q3': 'q14',
    'q4': 'q15',
    'q22': 'q16',
    'q23': 'q17',
    'q24': 'q18',
    'q25': 'q19',
    'q26': 'q20',
    'q27': 'q21',
    'q28': 'q22',
    'q29': 'q23',
    'q30': 'q24',
    'q31': 'q25',
    'q32': 'q26',
    'q33': 'q27',
    'q19': 'q28',
    'q20': 'q29',
    'q21': 'q30',
    'q16': 'q31',
    'q17': 'q32',
    'q18': 'q33',
    'q41': 'q34',
    'q42': 'q35',
    'q43': 'q36',
    'q44':  'q37',
    'q45':  'q38',
    'q34':  'q39',
    'q35':  'q40',
    'q36': 'q41',
    'q37': 'q42',
    'q13': 'q43',
    'q14': 'q44',
    'q15': 'q45',
}

enemRosa = enemRosa.loc[:, list(col_mapping.keys())]
enemRosa = enemRosa.rename(columns=col_mapping).reset_index(drop=True)
enemRosa

,nota,q1,q2,q3,q4,q5,q6,q7,q8,q9,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,373.8,A,D,A,D,E,D,B,E,B,...,C,A,C,A,E,A,B,A,C,E
1,390.1,B,B,D,D,B,A,B,C,A,...,D,D,D,B,A,B,B,B,C,A
2,430.4,B,E,C,D,B,A,B,A,E,...,*,D,D,B,C,D,A,D,D,C
3,567.3,A,B,B,D,C,E,B,A,E,...,C,B,C,D,B,A,B,B,D,B
4,532.2,E,B,E,B,E,E,A,B,E,...,B,A,B,D,A,D,C,A,D,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924206,570.1,C,B,A,D,E,E,D,E,B,...,C,D,B,D,A,C,B,C,E,B
924207,502.5,A,B,E,A,D,D,E,C,E,...,E,D,B,B,C,E,B,B,D,D
924208,524.0,B,A,E,C,C,E,E,E,B,...,D,D,B,B,D,C,A,C,B,A
924209,414.6,B,D,C,D,E,D,B,E,C,...,D,B,E,A,E,C,E,B,C,A
924210,409.0,A,D,C,C,E,D,B,B,D,...,B,A,A,D,A,C,B,C,D,E

# Processamento 2:

## Concatenando respostas|:

In [27]:
provaEnem = pd.concat([enemAmarela, enemAzul, enemCinza, enemRosa], ignore_index=True)
display(provaEnem)

,nota,q1,q2,q3,q4,q5,q6,q7,q8,q9,...,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45
0,483.8,B,A,C,C,E,E,B,E,E,...,A,D,E,E,A,C,C,B,B,D
1,513.6,E,E,B,E,D,E,E,E,E,...,C,C,D,B,C,E,C,E,A,E
2,576.6,B,E,E,A,E,E,B,C,E,...,C,C,C,A,E,D,A,B,D,C
3,455.4,B,B,C,A,C,D,C,B,E,...,C,B,A,C,E,C,B,B,E,A
4,618.2,B,A,C,A,C,E,D,D,E,...,C,B,C,B,E,D,C,D,D,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707736,570.1,C,B,A,D,E,E,D,E,B,...,C,D,B,D,A,C,B,C,E,B
3707737,502.5,A,B,E,A,D,D,E,C,E,...,E,D,B,B,C,E,B,B,D,D
3707738,524.0,B,A,E,C,C,E,E,E,B,...,D,D,B,B,D,C,A,C,B,A
3707739,414.6,B,D,C,D,E,D,B,E,C,...,D,B,E,A,E,C,E,B,C,A
3707740,409.0,A,D,C,C,E,D,B,B,D,...,B,A,A,D,A,C,B,C,D,E

## Dados das respostas:

In [28]:
# lista com os nomes das colunas que vão ser plotadas
colunas = ['q' + str(i) for i in range(1, 46)]

# criar um DataFrame vazio para armazenar os resultados
resultado = pd.DataFrame()

# loop para iterar sobre as colunas e criar os gráficos
for coluna in colunas:
    # obter os valores de value_counts()
    valores = provaEnem[coluna].value_counts()
    porcentagens = provaEnem[coluna].value_counts(normalize=True)

    # adicionar os valores e porcentagens como colunas no DataFrame resultado
    #resultado[coluna + '_valores'] = valores
    resultado[coluna + '_porcentagens'] = porcentagens

# Ordenar as linhas em ordem alfabética pelas letras que representam as alternativas
resultado_antes = resultado.sort_index()

# Excluir as linhas que têm '*' e '.' como representantes
resultado_depois = resultado_antes.drop(['.', '*'])

# exibir o resultado final
display(resultado_antes)

,q1_porcentagens,q2_porcentagens,q3_porcentagens,q4_porcentagens,q5_porcentagens,q6_porcentagens,q7_porcentagens,q8_porcentagens,q9_porcentagens,q10_porcentagens,...,q36_porcentagens,q37_porcentagens,q38_porcentagens,q39_porcentagens,q40_porcentagens,q41_porcentagens,q42_porcentagens,q43_porcentagens,q44_porcentagens,q45_porcentagens
*,0.001079,0.001638,0.001438,0.001302,0.001542,0.001629,0.000834,0.001248,0.001703,0.001396,...,0.001256,0.001098,0.001263,0.000962,0.001474,0.001268,0.000976,0.001420,0.001770,0.000945
.,0.002487,0.001593,0.001438,0.002207,0.000887,0.000792,0.003213,0.001063,0.000935,0.001416,...,0.001181,0.001792,0.000992,0.001200,0.001247,0.000948,0.001512,0.002487,0.001033,0.002897
A,0.140391,0.257324,0.163252,0.295829,0.172963,0.096656,0.247477,0.173349,0.093199,0.220430,...,0.066258,0.154179,0.168371,0.247110,0.346888,0.167262,0.201774,0.134191,0.215775,0.172763
B,0.229363,0.241972,0.111205,0.111263,0.100663,0.026127,0.302391,0.319294,0.216199,0.262412,...,0.123580,0.241655,0.262123,0.307791,0.260446,0.221336,0.299166,0.361223,0.058969,0.226362
C,0.317120,0.082937,0.409827,0.304837,0.181153,0.089085,0.176649,0.105469,0.127904,0.180017,...,0.457452,0.223406,0.215518,0.123186,0.138613,0.232699,0.286909,0.240972,0.181961,0.239992
D,0.178297,0.157525,0.129311,0.205199,0.177151,0.285860,0.158892,0.096724,0.085001,0.210257,...,0.116854,0.279409,0.192651,0.189461,0.136903,0.301835,0.132690,0.164697,0.302173,0.225015
E,0.131263,0.257011,0.183529,0.079364,0.365641,0.499851,0.110544,0.302855,0.475060,0.124071,...,0.233419,0.098462,0.159082,0.130290,0.114429,0.074651,0.076972,0.095009,0.238320,0.132026

In [29]:
# exibir o resultado final
display(resultado_depois)

,q1_porcentagens,q2_porcentagens,q3_porcentagens,q4_porcentagens,q5_porcentagens,q6_porcentagens,q7_porcentagens,q8_porcentagens,q9_porcentagens,q10_porcentagens,...,q36_porcentagens,q37_porcentagens,q38_porcentagens,q39_porcentagens,q40_porcentagens,q41_porcentagens,q42_porcentagens,q43_porcentagens,q44_porcentagens,q45_porcentagens
A,0.140391,0.257324,0.163252,0.295829,0.172963,0.096656,0.247477,0.173349,0.093199,0.220430,...,0.066258,0.154179,0.168371,0.247110,0.346888,0.167262,0.201774,0.134191,0.215775,0.172763
B,0.229363,0.241972,0.111205,0.111263,0.100663,0.026127,0.302391,0.319294,0.216199,0.262412,...,0.123580,0.241655,0.262123,0.307791,0.260446,0.221336,0.299166,0.361223,0.058969,0.226362
C,0.317120,0.082937,0.409827,0.304837,0.181153,0.089085,0.176649,0.105469,0.127904,0.180017,...,0.457452,0.223406,0.215518,0.123186,0.138613,0.232699,0.286909,0.240972,0.181961,0.239992
D,0.178297,0.157525,0.129311,0.205199,0.177151,0.285860,0.158892,0.096724,0.085001,0.210257,...,0.116854,0.279409,0.192651,0.189461,0.136903,0.301835,0.132690,0.164697,0.302173,0.225015
E,0.131263,0.257011,0.183529,0.079364,0.365641,0.499851,0.110544,0.302855,0.475060,0.124071,...,0.233419,0.098462,0.159082,0.130290,0.114429,0.074651,0.076972,0.095009,0.238320,0.132026

In [30]:
# Gabarito
gabarito = ['B', 'E', 'E', 'A', 'A', 'E', 'B', 'E', 'E', 'B', 'A', 'D', 'E', 'A', 'D', 'D', 'A', 'D', 'A', 'E', 'A', 'B', 'C', 'E', 'D', 'D', 'D', 'B', 'C', 'B', 'C', 'B', 'C', 'C', 'A', 'C', 'B', 'C', 'D', 'A', 'D', 'C', 'C', 'E', 'B']

# Criando um novo DataFrame com as porcentagens de acerto da questão baseado no gabarito
porcentagens_acerto = pd.DataFrame()
for questao, resposta in enumerate(gabarito, start=1):
    porcentagens_acerto[f'q{questao}_acerto'] = [resultado[f'q{questao}_porcentagens'][ord(resposta) - 65]]

# Exibindo o resultado
porcentagens_acerto

,q1_acerto,q2_acerto,q3_acerto,q4_acerto,q5_acerto,q6_acerto,q7_acerto,q8_acerto,q9_acerto,q10_acerto,...,q36_acerto,q37_acerto,q38_acerto,q39_acerto,q40_acerto,q41_acerto,q42_acerto,q43_acerto,q44_acerto,q45_acerto
0,0.229363,0.257011,0.183529,0.304837,0.181153,0.499851,0.302391,0.302855,0.47506,0.262412,...,0.116854,0.241655,0.192651,0.24711,0.138613,0.167262,0.13269,0.164697,0.23832,0.226362

In [31]:
quest = input("Valor da questão?")

Valor da questão?6

In [32]:
# Encontrar a coluna com o maior valor
coluna_maior_valor = porcentagens_acerto.idxmax(axis=1).iloc[0]

# Obter os rótulos das 5 colunas com os maiores valores
maiores_colunas = porcentagens_acerto.iloc[0].nlargest(int(quest)).index

# Selecionar as 5 colunas com os maiores valores
dataset_maiores_colunas = porcentagens_acerto[maiores_colunas]

print("Dataset com as 5 colunas que possuem os maiores valores:")
dataset_maiores_colunas

Dataset com as 5 colunas que possuem os maiores valores:

   q6_acerto  q28_acerto  q24_acerto  q9_acerto  q13_acerto  q22_acerto
0   0.499851    0.499524    0.492999    0.47506    0.408803    0.377267

In [33]:
# Encontrar a coluna com o maior valor
coluna_maior_valor = porcentagens_acerto.idxmax(axis=1).iloc[0]

# Obter os rótulos das 5 colunas com os maiores valores
menores_colunas = porcentagens_acerto.iloc[0].nsmallest(int(quest)).index

# Selecionar as 5 colunas com os maiores valores
dataset_menores_colunas = porcentagens_acerto[menores_colunas]

print("Dataset com as 5 colunas que possuem os menores_colunas:")
dataset_menores_colunas

Dataset com as 5 colunas que possuem os menores_colunas:

   q25_acerto  q33_acerto  q36_acerto  q21_acerto  q42_acerto  q40_acerto
0    0.074206    0.110852    0.116854    0.117353     0.13269    0.138613

# Salvando:

In [35]:
# salvar o resultado em um arquivo CSV com o nome personalizado

resultado.to_csv("/content/drive/MyDrive/Pesquisa_Enem/Resultados/" + f"resultados_{amostra}")
porcentagens_acerto.to_csv("/content/drive/MyDrive/Pesquisa_Enem/Resultados/" + f"Porcentagem_quests_{amostra}")
dataset_maiores_colunas.to_csv("/content/drive/MyDrive/Pesquisa_Enem/Resultados/" + f"quest_easy_{amostra}")
dataset_menores_colunas.to_csv("/content/drive/MyDrive/Pesquisa_Enem/Resultados/" + f"resquest_hard_{amostra}")

print(f"O dataset foi salvo como resultados.")

O dataset foi salvo como resultados.